core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from mercatorio import views

urlpatterns = [
    path('', include('mercatorio.urls')),
    path('admin/', admin.site.urls),
    path('api/certidoes', views.mock_certificate_api, name='mock-certidoes'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('hidden/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
]

mercatorio/urls.py
from django.urls import path

from . import views

app_name = 'mercatorio'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('credores', views.create_creditor, name='create'),
    path('credores/<int:pk>/documentos', views.upload_document_view, name='upload-document'),
    path('credores/<int:pk>/certidoes', views.upload_certificate_view, name='upload_certificate'),
    path('credores/<int:pk>/buscar-certidoes', views.search_certificates_view, name='search_certificates'),
    path('credores/<int:pk>', views.creditor_detail_view, name='creditor_detail'),
]

mercatorio/models.py
from django.db import models
from django.utils import timezone

from .utils.validate_document import validate_document_extension, validate_file_size, validate_certificate_extension

# Create your models here.
class Creditor(models.Model):
    name = models.CharField(max_length=255)
    cpf_cnpj = models.CharField(max_length=20, unique=True)
    email = models.EmailField()
    phone = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.name} ({self.cpf_cnpj})"

class Precatorio(models.Model):
    precatorio_number = models.CharField(max_length=100, unique=True)
    nominal_value = models.DecimalField(max_digits=15, decimal_places=2)
    forum = models.CharField(max_length=255)
    publication_date = models.DateField()

    creditor = models.ForeignKey(Creditor, on_delete=models.CASCADE, related_name='precatorios')

    def __str__(self):
        return f"Precatório {self.precatorio_number} - {self.creditor.name}"

class PersonalDocument(models.Model):
    class DocumentType(models.TextChoices):
        RG = 'RG', 'RG'
        CPF = 'CPF', 'CPF'
        CNH = 'CNH', 'CNH'
        BIRTH_CERTIFICATE = 'birth_certificate', 'Certidão de Nascimento'
        PROOF_OF_ADDRESS = 'proof_of_address', 'Comprovante de endereço'

    doc_type = models.CharField(max_length=50, choices=DocumentType.choices)
    file = models.FileField(
        upload_to='documents/',
        validators=[validate_document_extension, validate_file_size],
        null=True, 
        blank=True, 
    )
    file_url = models.URLField()
    submitted_at = models.DateTimeField(default=timezone.now)

    creditor = models.ForeignKey(Creditor, on_delete=models.CASCADE, related_name='documents')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.file and not self.file_url:
            self.file_url = self.file.url
            PersonalDocument.objects.filter(pk=self.pk).update(file_url=self.file_url)

    def __str__(self):
        return f"{self.get_doc_type_display()} - {self.creditor.name}"

class Certificate(models.Model):
    class CertificateType(models.TextChoices):
        FEDERAL = 'federal', 'Federal'
        STATE = 'state', 'Estadual'
        MUNICIPAL = 'municipal', 'Municipal'
        LABOR = 'labor', 'Trabalhista'

    class CertificateOrigin(models.TextChoices):
        MANUAL = 'manual', 'Manual'
        API = 'api', 'API'

    class CertificateStatus(models.TextChoices):
        NEGATIVE = 'negative', 'Negativa'
        POSITIVE = 'positive', 'Positiva'
        INVALID = 'invalid', 'Invalida'
        PENDING = 'pending', 'Pendente'

    cert_type = models.CharField(max_length=50, choices=CertificateType.choices)
    origin = models.CharField(max_length=20, choices=CertificateOrigin.choices)
    file = models.FileField(
        upload_to='certificates/',
        validators=[validate_certificate_extension, validate_file_size],
        null=True, 
        blank=True, 
    )
    file_url = models.URLField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=CertificateStatus.choices, default=CertificateStatus.PENDING)
    received_at = models.DateTimeField(default=timezone.now)

    creditor = models.ForeignKey(Creditor, on_delete=models.CASCADE, related_name='certificates')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.file and not self.file_url:
            self.file_url = self.file.url
            Certificate.objects.filter(pk=self.pk).update(file_url=self.file_url)

    def __str__(self):
        return f"{self.cert_type} - {self.creditor.name} ({self.status})"

mercatorio/forms.py
from django import forms
from .models import PersonalDocument, Certificate

from .utils.validate_document import validate_document_extension, validate_file_size

class PersonalDocumentForm(forms.ModelForm):
    class Meta:
        model = PersonalDocument
        fields = ['doc_type', 'file']
        labels = {
            'doc_type': 'Tipo de Documento',
            'file': 'Documento',
        }
        widgets = {
            'doc_type': forms.Select(attrs={'class': 'form-select', 'requered': 'true'}),
            'file': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'accept': '.pdf,.jpg,.jpeg,.png'
            }),
        }

    def clean_files(self):
        file = self.cleaned_data.get('file')

        validate_document_extension(file)
        validate_file_size(file)

        return file

class CertificateForms(forms.ModelForm):
    class Meta:
        model = Certificate
        fields = ['cert_type','origin','status','file']
        labels = {
            'cert_type': 'Tipo de Certificado',
            'origin': 'Origen',
            'status': 'Estado',
            'file': 'Certificado',
        }
        widgets = {
            'cert_type': forms.Select(attrs={'class': 'form-select', 'requered': 'true'}),
            'origin': forms.Select(attrs={'class': 'form-select', 'requered': 'true'}),
            'status': forms.Select(attrs={'class': 'form-select', 'requered': 'true'}),
            'file': forms.ClearableFileInput(attrs={
                'class': 'form-control',
                'accept': '.pdf,.jpg,.jpeg,.png'
            }),
        }
    
    def clean_files(self):
        file = self.cleaned_data.get('file')

        validate_document_extension(file)
        validate_file_size(file)

        return file

mercatorio/views.py
from django.shortcuts import get_object_or_404, render, redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

import random

import requests
from django.utils import timezone

from .serializers import CreditorSerializer, CreditorDetailSerializer
from .models import Creditor, PersonalDocument, Certificate
from mercatorio.forms import PersonalDocumentForm, CertificateForms

from .schemas import create_creditor_schema, mock_cert_schema, creditor_detail_schema, search_certificates_schema

# Create your views here.
def index_view(request):
    certificate = Certificate.objects.all
    return render(request, 'mercatorio/index.html', {'certificates': certificate})

@create_creditor_schema
@api_view(['POST'])
def create_creditor(request):
    cpf_cnpj = request.data.get('cpf_cnpj')
    if cpf_cnpj and Creditor.objects.filter(cpf_cnpj=cpf_cnpj).exists():
        return Response({'message': 'cpf/cnpj já existe.'}, status=status.HTTP_409_CONFLICT)
    serializer = CreditorSerializer(data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data, status=status.HTTP_201_CREATED)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

def upload_document_view(request, pk):
    creditor = get_object_or_404(Creditor, pk=pk)
    Personal_document = PersonalDocument.objects.filter(creditor=creditor)
    form = PersonalDocumentForm()
    if request.method == 'POST':
        form = PersonalDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document = form.save(commit=False)
            document.creditor = creditor
            document.save()
    return render(request, 'mercatorio/document.html', {'form': form, 'creditor': creditor, 'documents': Personal_document})

def upload_certificate_view(request, pk):
    creditor = get_object_or_404(Creditor, pk=pk)
    form = CertificateForms()
    certificate = Certificate.objects.filter(creditor=creditor)
    if request.method == 'POST':
        form = CertificateForms(request.POST, request.FILES)
        if form.is_valid():
            certificate = form.save(commit=False)
            certificate.creditor = creditor
            certificate.save()
            return redirect('mercatorio:upload_certificate', pk=creditor.id)
    return render(request, 'mercatorio/certificate.html', {'form': form, 'creditor': creditor, 'certificates': certificate})

@mock_cert_schema
@api_view(['GET'])
def mock_certificate_api(request):
    cpf_cnpj = request.GET.get('cpf_cnpj')
    if not cpf_cnpj:
        return Response({'message': 'cpf_cnpj é obrigatório'}, status=status.HTTP_400_BAD_REQUEST)

    tipos = ['federal', 'state', 'municipal', 'labor']
    status_options = ['negative', 'positive', 'invalid', 'pending']

    certidoes = []
    for tipo in tipos:
        certidoes.append({
            'tipo': tipo,
            'status': random.choice(status_options),
            'file_url': f"/media/certificates/{tipo}_fake_certidao.pdf"
        })
    
    return Response({
        'cpf_cnpj': cpf_cnpj,
        'certidoes': certidoes
    }, status=status.HTTP_200_OK)

@search_certificates_schema
@api_view(['POST'])
def search_certificates_view(request, pk):
    creditor = get_object_or_404(Creditor, pk=pk)
    cpf_cnpj = creditor.cpf_cnpj

    response = requests.get('http://localhost:8000/api/certidoes', params={'cpf_cnpj': cpf_cnpj})

    if response.status_code != 200:
        return Response({'message': 'rro ao consultar certidões'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    data = response.json()

    for cert in data['certidoes']:
        Certificate.objects.create(
            creditor=creditor,
            cert_type=cert['tipo'],
            status=cert['status'],
            origin='api',
            file_url=cert['file_url'],
            received_at=timezone.now()
        )

    return Response({'message': 'Certidões geradas com sucesso'}, status = status.HTTP_200_OK)

@creditor_detail_schema
@api_view(['GET'])
def creditor_detail_view(request, pk):
    creditor = get_object_or_404(Creditor, pk=pk)
    serializer = CreditorDetailSerializer(creditor)
    return Response(serializer.data)

mercatorio/templates/mercatorio/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Mercatório{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            {% block navbar %}
                <span class="navbar-text">Mercatório</span>
            {% endblock %}
        </div>
    </nav>
    
    <div class="container mt-5">
        {% block content %}
            
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.min.js" integrity="sha384-RuyvpeZCxMJCqVUGFI0Do1mQrods/hhxYlcVfGPOfQtPJh0JCw12tUAZ/Mv10S7D" crossorigin="anonymous"></script>
  </body>
</html>

mercatorio/templates/mercatorio/certificate.html
{% extends "mercatorio/base.html" %}

{% block title %}Certidões{% endblock %}

{% block navbar %}
    <span class="navbar-text">{{ creditor.name }} - {{ creditor.cpf_cnpj }}</span>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header bg-dark text-white">
            Enviar Documento Pessoal
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}
                
                <div class="d-flex justify-content-end mt-5">
                    <button class="btn btn-primary btn-sm" type="submit">Enviar Documento</button>
                </div>
            </form>
        </div>
    </div>
    <br>
    <hr>
    <br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Tipo Certidão</th>
                <th scope="col">Origem</th>
                <th scope="col">Status</th>
                <th scope="col">Url do arquivo</th>
            </tr>
        </thead>
        <tbody>
            {% for certificate in certificates %}
                <tr>
                    <td>{{ certificate.get_cert_type_display }}</td>
                    <td>{{ certificate.get_origin_display }}</td>
                    <td>{{ certificate.get_status_display }}</td>
                    <td>
                        <a href="{{ certificate.file_url }}" target="_blank">{{ certificate.file_url }}</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mercatorio/templates/mercatorio/document.html
{% extends "mercatorio/base.html" %}

{% block title %}Documentos Pessoais{% endblock %}

{% block navbar %}
    <span class="navbar-text">{{ creditor.name }} - {{ creditor.cpf_cnpj }}</span>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header bg-dark text-white">
            Enviar Documento Pessoal
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}
                
                <div class="d-flex justify-content-end mt-5">
                    <button class="btn btn-primary btn-sm" type="submit">Enviar Documento</button>
                </div>
            </form>
        </div>
    </div>
    <br>
    <hr>
    <br>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Tipo</th>
                <th scope="col">Url Documento</th>
            </tr>
        </thead>
        <tbody>
            {% for doc in documents %}
                <tr>
                    <td>{{ doc.get_doc_type_display }}</td>
                    <td>
                        <a href="{{ doc.file_url }}" target="_blank">{{ doc.file_url }}</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mercatorio/templates/mercatorio/index.html
{% extends "mercatorio/base.html" %}

{% block title %}Pagina Inicial{% endblock %}

{% block navbar %}
    <span class="navbar-text">Mercatório</span>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header bg-dark text-white">
            Bem Vindo ao Mercatório!
        </div>
        <div class="card-body">
            <h5 class="card-title">Atualizações de certificações</h5>
            <p class="card-text">As certificações são atualizadas a cada 24 horas.</p>
            {% if certificates.count > 0 %}
                <code>Total de {{ certificates.count }} certificações.</code>
                <code>Ultima atualização foi {{ certificates.first.received_at }}</code>
            {% else %}
                <code>Não há certificações</code>
            {% endif %}
        </div>
    </div>
{% endblock %}